// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMF2N_nsOmlwTxWDSQE-4jUIfPwzX7cF0',
    appId: '1:654123967272:web:3060d126149f4f9444a61d',
    messagingSenderId: '654123967272',
    projectId: 'coins-291a1',
    authDomain: 'coins-291a1.firebaseapp.com',
    storageBucket: 'coins-291a1.appspot.com',
    measurementId: 'G-312G06CT1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgsLZVFYgzAPikxVH1sGN4D9d3-hfIL4',
    appId: '1:654123967272:android:52a987efdd6f7ffd44a61d',
    messagingSenderId: '654123967272',
    projectId: 'coins-291a1',
    storageBucket: 'coins-291a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHjSxKei89PULY1rnsSkoxv72XXXv7zCo',
    appId: '1:654123967272:ios:80c52edadacf90f544a61d',
    messagingSenderId: '654123967272',
    projectId: 'coins-291a1',
    storageBucket: 'coins-291a1.appspot.com',
    androidClientId: '654123967272-8jjrdum3qhejr6u00squ6mhcv6oqnpcj.apps.googleusercontent.com',
    iosClientId: '654123967272-adabh0bncnl1s9nm8hk96s3brvb5f7uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoCurrency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHjSxKei89PULY1rnsSkoxv72XXXv7zCo',
    appId: '1:654123967272:ios:80c52edadacf90f544a61d',
    messagingSenderId: '654123967272',
    projectId: 'coins-291a1',
    storageBucket: 'coins-291a1.appspot.com',
    androidClientId: '654123967272-8jjrdum3qhejr6u00squ6mhcv6oqnpcj.apps.googleusercontent.com',
    iosClientId: '654123967272-adabh0bncnl1s9nm8hk96s3brvb5f7uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoCurrency',
  );
}
